steve_frontend_homepage:
    pattern:     /{page}
    defaults: { _controller: SteveFrontendBundle:Default:index }
steve_frontend_homepage_main:
    pattern:     /
    defaults: { _controller: SteveFrontendBundle:Default:index }
SteveFrontendBundle_ajax_update_mydata:
  pattern:  /update/data/from/ajax/call
  defaults: { _controller: SteveFrontendBundle:Default:updateData }
SteveFrontendBundle_ajax_load_mydata:
  pattern:  /load/data/from/ajax/call
  defaults: { _controller: SteveFrontendBundle:Ajax:loadAjaxData }
SteveFrontendBundle_interface:
  pattern:  /load/data/from/interface/call
  defaults: { _controller: SteveFrontendBundle:Interface:loadInterfaceData }
SteveFrontendBundle_crontask:
  pattern:  /crontasks/test
  defaults: { _controller: SteveFrontendBundle:CronTask:test }
SteveFrontendBundle_mail:
  pattern:  /mail/send
  defaults: { _controller: SteveFrontendBundle:Mail:send }
